### ISSUE TITLE
Twitter ApiRequestError

### ISSUE THREAD

**Issue by Eccleria** [Titch88/ewibot#104]
```javascript
/home/ewibot/ewibot/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:57
        return new types_1.ApiRequestError('Request failed.', {
               ^

ApiRequestError: Request failed.
    at RequestHandlerHelper.createRequestError (/home/ewibot/ewibot/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:57:16)
    at RequestHandlerHelper.requestErrorHandler (/home/ewibot/ewibot/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:216:21)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  error: true,
  type: 'request'
}
```

**Comment by Eccleria** [comment]
Apparently a Twitter API side error. 
https://github.com/PLhery/node-twitter-api-v2/issues/92
