### ISSUE TITLE
Twitter Missing permissions

### ISSUE THREAD

**Issue by Eccleria** [Titch88/ewibot#106]
```javascript
/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Permissions
    at RequestHandler.execute (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/home/ewibot/ewibot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15)
    at async file:///home/ewibot/ewibot/src/admin/twitter.js:87:38 {
  method: 'post',
  path: '/channels/816986951021756446/messages',
  code: 50013,
  httpStatus: 403,
  requestData: {
    json: {
      content: 'https://twitter.com/andartapictures/status/1592502782648467456',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
```

**Comment by Eccleria** [comment]
Solved with proper Discord channel permission overwrite
