### ISSUE TITLE
Twitter User aborted a request

### ISSUE THREAD

**Issue by Eccleria** [Titch88/ewibot#114]
```javascript
/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:201
        throw new HTTPError(error.message, error.constructor.name, error.status, request);
              ^

HTTPError [AbortError]: The user aborted a request.
    at RequestHandler.execute (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:201:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/home/ewibot/ewibot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15)
    at async file:///home/ewibot/ewibot/src/admin/twitter.js:87:38 {
  code: 500,
  method: 'post',
  path: '/channels/816986951021756446/messages',
  requestData: {
    json: {
      content: 'https://twitter.com/andartapictures/status/1601161027378356224',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
```

**Comment by Eccleria** [comment]
It should be only rare issue, because of upload getting stuck.
