### ISSUE TITLE
admin_logs addAdminLogs db undefined

### ISSUE THREAD

**Issue by Eccleria** [Titch88/ewibot#77]
```javascript
file:///home/ewibot/ewibot/src/admin/listeners.js:465
      addAdminLogs(msg.client.db, msg.id, "frequent", 6)
                              ^

TypeError: Cannot read properties of undefined (reading 'db')
    at file:///home/ewibot/ewibot/src/admin/listeners.js:465:31
    at Array.forEach (<anonymous>)
    at Client.onMessageDelete (file:///home/ewibot/ewibot/src/admin/listeners.js:464:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

**Comment by Eccleria** [comment]
fixed in [e0d28e1](https://github.com/Titch88/ewibot/pull/79/commits/e0d28e1545b50f5b8a0c0c54357d399bd678ab45)
