### ISSUE TITLE
LogsRemover result type error

### ISSUE THREAD

**Issue by Eccleria** [Titch88/ewibot#80]
```javascript
logsRemover
file:///home/ewibot/ewibot/src/admin/utils.js:603
      if (result.includes(cur.id)) return acc; //if no diff
                 ^

TypeError: result.includes is not a function
    at file:///home/ewibot/ewibot/src/admin/utils.js:603:18
    at Array.reduce (<anonymous>)
    at logsRemover (file:///home/ewibot/ewibot/src/admin/utils.js:602:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Eccleria** [comment]
fixed in #79 [4efcca1](https://github.com/Titch88/ewibot/pull/79/commits/4efcca114facc1f7b49502a54bdbee73f8672270)
