### ISSUE TITLE
Twitter stream exists Interaction Unknown

### ISSUE THREAD

**Issue by Eccleria** [Titch88/ewibot#85]
```javascript
/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async CommandInteraction.reply (/home/ewibot/ewibot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:103:5) {
  method: 'post',
  path: '/interactions/1022198118755868782/aW50ZXJhY3Rpb246MTAyMjE5ODExODc1NTg2ODc4MjpvTW00N01qcEJrWXNiVnFwQ1o4Z29FdXNHbHZqOExiSHF4SVhiRzREVDlESnRpdkdKRlFOdHpUMHBaQVpYSDl1THY0WWVtS1hZN1F1cWtjeDMxQkhQUjRUekU5MDZqS0I2RG9nWnVNcDB0dk8zUk9KemI2Vk1HbnFDZkxrWXRNcw/callback',
  code: 10062,
  httpStatus: 404,
  requestData: {
    json: {
      type: 4,
      data: {
        content: 'Un stream existe déjà.',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: 64,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined
      }
    },
    files: []
  }
}
```

**Comment by Eccleria** [comment]
**stream removed in** 5c1174f
