### ISSUE TITLE
Admin_logs messageUpdate DiscordAPIError : entity too large

### ISSUE THREAD

**Issue by Eccleria** [Titch88/ewibot#92]
```javascript
finishEmbed list error
 Message modifié 2022-10-10T17:19:42.072Z DiscordAPIError: Request entity too large
    at RequestHandler.execute (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ThreadChannel.send (/home/ewibot/ewibot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15)
    at async finishEmbed (file:///home/ewibot/ewibot/src/admin/utils.js:102:28)
    at async Client.onMessageUpdate (file:///home/ewibot/ewibot/src/admin/listeners.js:692:23) {
  method: 'post',
  path: '/channels/1012365101594058762/messages',
  code: 40005,
  httpStatus: 413,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: [Array],
      sticker_ids: undefined
    },
    files: [ [Object] ]
  }
}
```

**Comment by Eccleria** [comment]
```js
finishEmbed list error
 Message supprimé 2023-06-12T13:20:15.600Z DiscordAPIError: Request entity too large
    at RequestHandler.execute (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/ewibot/ewibot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ThreadChannel.send (/home/ewibot/ewibot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:177:15)
    at async finishEmbed (file:///home/ewibot/ewibot/src/admin/utils.js:106:28)
    at async Client.onMessageDelete (file:///home/ewibot/ewibot/src/admin/listeners.js:555:25) {
  method: 'post',
  path: '/channels/1012365101594058762/messages',
  code: 40005,
  httpStatus: 413,
  requestData: {
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: [Array],
      sticker_ids: undefined,
      thread_name: undefined
    },
    files: [ [Object] ]
  }
}
```
