### ISSUE TITLE
Admin/role.js undefined roleId

### ISSUE THREAD

**Issue by Eccleria** [Titch88/ewibot#93]
```javascript
file:///home/ewibot/ewibot/src/admin/role.js:71
  const roleIdtoChg = roleParam.roleId; //get the role id associated to the triggering reaction
                                ^

TypeError: Cannot read properties of undefined (reading 'roleId')
    at roleRemove (file:///home/ewibot/ewibot/src/admin/role.js:71:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.onReactionRemove (file:///home/ewibot/ewibot/src/listeners.js:173:5)
```

**Comment by Eccleria** [comment]
new occurrence
